# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "air"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./air/main ."
# Binary file yields from `cmd`.
bin = "air/main"
# Watch these filename extensions.
include_ext = ["go", "html"]

[misc]
# Delete air directory on exit
clean_on_exit = true
