// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package apigen

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Bio     *string `json:"bio,omitempty"`
	IconUrl *string `json:"icon_url,omitempty"`
	Id      uint    `json:"id"`
	Name    string  `json:"name"`
}

// UserToSave defines model for UserToSave.
type UserToSave struct {
	Bio     *string `json:"bio,omitempty"`
	IconUrl *string `json:"icon_url,omitempty" validate:"url"`
	Name    string  `json:"name" validate:"max=12"`
}

// UserIdPath defines model for UserIdPath.
type UserIdPath = uint

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserToSave

// PutUsersJSONRequestBody defines body for PutUsers for application/json ContentType.
type PutUsersJSONRequestBody = UserToSave
