openapi: 3.0.3
info:
  title: Sample APIs
  version: "1.0"
servers:
  - url: "https://localhost:8080"
    description: local
  - url: "https://example.com"
    description: develop
tags:
  - name: "User"
paths:
  /healthz:
    get:
      summary: "health check"
      description: "health check"
      responses:
        200:
          description: success
  /users:
    post:
      tags:
        - "User"
      summary: "create user"
      description: "create user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserToSave"
      responses:
        201:
          description: success
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - "User"
      summary: "update user"
      description: "update user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserToSave"
      responses:
        204:
          description: success
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /users/{userId}:
    get:
      tags:
        - "User"
      summary: "get user"
      description: "get user"
      parameters:
        - $ref: "#/components/parameters/UserIdPath"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  parameters:
    UserIdPath:
      name: userId
      in: path
      required: true
      schema:
        type: integer
        x-go-type: uint
      description: user id
      example: 1
  schemas:
    Error:
      $ref: "./models/Error.yaml"
    User:
      $ref: "./models/User.yaml"
    UserToSave:
      $ref: "./models/UserToSave.yaml"
